### ISSUE TITLE
Investigate crash in newrelic on saving tiles to s3 cache 

### ISSUE THREAD

**Issue by hampelm** [LocalData/localdata-tiles#162]
```
May 04 16:53:17 localdata-tiles app/web.1:  info at=s3_features_cache event=miss reason=absent name=/production-tiles/features/layers/e71bd314bf9501fe92ae65376a1ae2bad2c422ea/tiles/15/9100/12348.png 
May 04 16:53:17 localdata-tiles app/web.1:  /app/node_modules/newrelic/lib/transaction/tracer/index.js:172 
May 04 16:53:17 localdata-tiles app/web.1:        throw err 
May 04 16:53:17 localdata-tiles app/web.1:        ^ 
May 04 16:53:17 localdata-tiles app/web.1:  Error: `value` required in setHeader("x-amz-meta-count", value). 
May 04 16:53:17 localdata-tiles app/web.1:      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11) 
May 04 16:53:17 localdata-tiles app/web.1:      at new ClientRequest (_http_client.js:80:14) 
May 04 16:53:17 localdata-tiles app/web.1:      at Object.exports.request (http.js:31:10) 
May 04 16:53:17 localdata-tiles app/web.1:      at makeRequest (/app/node_modules/newrelic/lib/instrumentation/core/http.js:298:31) 
May 04 16:53:17 localdata-tiles app/web.1:      at instrumentRequest (/app/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:28:19) 
May 04 16:53:17 localdata-tiles app/web.1:      at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
May 04 16:53:17 localdata-tiles app/web.1:      at Tracer.addSegment (/app/node_modules/newrelic/lib/transaction/tracer/index.js:67:48) 
May 04 16:53:17 localdata-tiles app/web.1:      at instrumentOutbound (/app/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:19:23) 
May 04 16:53:17 localdata-tiles app/web.1:      at Object.wrappedRequest [as request] (/app/node_modules/newrelic/lib/instrumentation/core/http.js:292:14) 
May 04 16:53:17 localdata-tiles app/web.1:      at Object.exports.request (https.js:163:15) 
May 04 16:53:17 localdata-tiles app/web.1:      at makeRequest (/app/node_modules/newrelic/lib/instrumentation/core/http.js:298:31) 
May 04 16:53:17 localdata-tiles app/web.1:      at instrumentRequest (/app/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:28:19) 
May 04 16:53:17 localdata-tiles app/web.1:      at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
May 04 16:53:17 localdata-tiles app/web.1:      at Tracer.addSegment (/app/node_modules/newrelic/lib/transaction/tracer/index.js:67:48) 
May 04 16:53:17 localdata-tiles app/web.1:      at instrumentOutbound (/app/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:19:23) 
May 04 16:53:17 localdata-tiles app/web.1:      at Object.wrappedRequest [as request] (/app/node_modules/newrelic/lib/instrumentation/core/http.js:292:14) 
May 04 16:53:17 localdata-tiles app/web.1:      at Client.request (/app/node_modules/knox/lib/client.js:287:42) 
May 04 16:53:17 localdata-tiles app/web.1:      at Client.put (/app/node_modules/knox/lib/client.js:326:15) 
May 04 16:53:17 localdata-tiles app/web.1:      at Client.putBuffer (/app/node_modules/knox/lib/client.js:448:18) 
May 04 16:53:17 localdata-tiles app/web.1:      at ServerResponse.res.send (/app/lib/cache/s3-cache-features.js:122:18) 
May 04 16:53:17 localdata-tiles app/web.1:      at handleData (/app/lib/controllers/features.js:146:9) 
May 04 16:53:17 localdata-tiles app/web.1:      at PassThrough.<anonymous> (/app/lib/controllers/util.js:64:5) 
May 04 16:53:17 localdata-tiles app/web.1:      at emitNone (events.js:72:20) 
May 04 16:53:17 localdata-tiles app/web.1:      at PassThrough.emit (events.js:166:7) 
May 04 16:53:17 localdata-tiles heroku/router:  at=error code=H13 desc="Connection closed without response" method=GET path="/features/layers/e71bd314bf9501fe92ae65376a1ae2bad2c422ea/tiles/15/9100/12348.png" host=localdata-tiles.herokuapp.com request_id=253fe5c3-4fd6-4dac-a53b-bd1380658248 fwd="98.14.98.17,205.251.250.106" dyno=web.1 connect=1ms service=1735ms status=503 bytes=0 
May 04 16:53:17 localdata-tiles app/web.1:      at endReadableNT (_stream_readable.js:905:12) 
May 04 16:53:17 localdata-tiles app/web.1:      at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
May 04 16:53:17 localdata-tiles app/web.1:      at doNTCallback2 (node.js:441:9) 
May 04 16:53:17 localdata-tiles app/web.1:      at process._tickCallback (node.js:355:17) 
```

**Comment by hampelm** [comment]
Looks like it could be a bug with request: https://github.com/request/request/issues/1522
